name: Deploy React App to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install deps
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # 4. Build React app
      - name: Build
        working-directory: frontend
        run: npm run build

      # 5. Copy build folder to EC2
      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/build/*"
          target: "/home/ubuntu/build"

      # 6. Deploy to nginx
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/build/* /var/www/html/
            sudo systemctl restart nginx
